import { useEffect, useState, type CSSProperties } from 'react';
import Plot from 'react-plotly.js';

type Question = { id:number; category:string; topic:string; prompt:string; option_a:string; option_b:string; option_c:string; option_d:string; correct_option:number; explanation:string };
type Analytics = { attempts:{date:string;score:number;total:number;durationSeconds:number}[]; byCategory:{category:string;total:number;correct:number;accuracy:number}[]; recommendations:string[] };
const API = '/api'; const categories = ['All','Quantitative','Logical Reasoning','Verbal','Data Interpretation'];
const letters = ['A','B','C','D'];
const lessons = [
 {icon:'%', area:'Quantitative', title:'Percentages without guesswork', time:'12 min lesson', formula:'Percentage change = (New value − Original value) ÷ Original value × 100', steps:['Read what is changing and write down the original value first.','Find the difference: increase means New − Original; decrease means Original − New.','Divide that difference by the original value, then multiply by 100.'], examples:[['A shirt price rises from ₹800 to ₹920. Find the increase percentage.','Difference = 920 − 800 = 120. Percentage increase = 120 ÷ 800 × 100 = 15%.','Answer: 15% increase.'],['A score falls from 75 to 60. Find the decrease percentage.','Difference = 75 − 60 = 15. Percentage decrease = 15 ÷ 75 × 100 = 20%.','Answer: 20% decrease.'],['Find 18% of ₹2,500.','18% = 18 ÷ 100. So 18 ÷ 100 × 2,500 = ₹450.','Answer: ₹450.']], tip:'The denominator is always the original value. A 20% increase followed by a 20% decrease does not bring a value back to where it started.'},
 {icon:'◫', area:'Quantitative', title:'Time, work & rates', time:'14 min lesson', formula:'Work rate = 1 ÷ days. Together: add the individual work rates. Time = 1 ÷ combined rate.', steps:['Treat the entire job as 1 piece of work.','Convert every worker’s time into the fraction of work they finish in one day.','Add rates when workers cooperate; subtract a rate if a worker leaves.'], examples:[['A can do a job in 12 days. What part is done in one day?','One full job in 12 days means A completes 1 ÷ 12 of the job each day.','Answer: 1/12 of the work per day.'],['A finishes in 12 days and B in 18 days. How long together?','Rates = 1/12 + 1/18. LCM 36: 3/36 + 2/36 = 5/36. Time = 1 ÷ (5/36) = 36/5 = 7.2 days.','Answer: 7.2 days.'],['A completes a job in 10 days; B in 15 days. How much work in 2 days together?','Daily rate = 1/10 + 1/15 = 3/30 + 2/30 = 1/6. In 2 days: 2 × 1/6 = 1/3.','Answer: one-third of the work.']], tip:'Never add days directly. Add rates: 1/12 + 1/18, not 12 + 18.'},
 {icon:'↗', area:'Logical Reasoning', title:'Number series patterns', time:'12 min lesson', formula:'No fixed formula: test in this order — differences → ratios → alternating terms → squares/cubes/primes.', steps:['Write the differences below consecutive terms. This finds the most common pattern.','If differences do not help, divide each term by the previous term to check multiplication.','Check odd-position and even-position terms separately before looking for special-number patterns.'], examples:[['Find the next term: 2, 6, 12, 20, 30, __','Differences: +4, +6, +8, +10. The difference grows by 2, so next difference is +12. 30 + 12 = 42.','Answer: 42.'],['Find the next term: 3, 6, 12, 24, __','Each term is multiplied by 2: 3×2=6, 6×2=12, 12×2=24. Next: 24×2=48.','Answer: 48.'],['Find the next term: 1, 4, 9, 16, __','These are squares: 1², 2², 3², 4². The next is 5² = 25.','Answer: 25.']], tip:'Do not choose a pattern after checking only two gaps. A valid rule must explain every number in the series.'},
 {icon:'Aa', area:'Verbal', title:'Grammar: subject–verb agreement', time:'11 min lesson', formula:'Singular subject → singular verb. Plural subject → plural verb. With neither/nor, the verb follows the nearer subject.', steps:['Find the subject doing the action; ignore words inside “of”, “with”, and similar phrases.','Decide if that subject is singular or plural.','For either/or and neither/nor, look at the subject closest to the verb.'], examples:[['Choose: The list of items (is / are) on the desk.','The subject is “list”, not “items”. List is singular, so it takes “is”.','Answer: The list of items is on the desk.'],['Choose: Neither the teacher nor the students (was / were) late.','The subject closest to the verb is “students”, which is plural. Use the plural verb “were”.','Answer: Neither the teacher nor the students were late.'],['Correct: She does not likes coffee.','After does/does not, use the base form of the verb. “Likes” becomes “like”.','Answer: She does not like coffee.']], tip:'Words such as each, every, everyone, and neither are normally singular: “Each student is ready.”'},
 {icon:'▦', area:'Data Interpretation', title:'Read tables & charts fast', time:'13 min lesson', formula:'Percentage change = (New − Old) ÷ Old × 100. Average = total of values ÷ number of values.', steps:['Read the chart title, units, and labels before calculating anything.','Identify exactly which two or three values the question needs.','Write the formula first, substitute values second, and round only at the end.'], examples:[['Revenue rises from ₹4 lakh to ₹5 lakh. Find percentage growth.','Change = 5 − 4 = 1 lakh. Growth = 1 ÷ 4 × 100 = 25%.','Answer: 25% growth.'],['Sales in three quarters are 120, 150, and 180. Find the average.','Total = 120 + 150 + 180 = 450. Average = 450 ÷ 3 = 150.','Answer: 150 units.'],['A pie-chart sector is 72°. What percentage does it represent?','A full circle is 360°. Share = 72 ÷ 360 × 100 = 20%.','Answer: 20%.']], tip:'In chart questions, the most common error is using the new value as the base. For growth, always divide by the old value.'}
];

export default function App() {
 const [page,setPage] = useState<'home'|'learn'|'quiz'|'analytics'>('home'); const [category,setCategory] = useState('All'); const [questions,setQuestions] = useState<Question[]>([]); const [current,setCurrent] = useState(0); const [answers,setAnswers] = useState<Record<number,number>>({}); const [started,setStarted] = useState(''); const [seconds,setSeconds] = useState(600); const [submitted,setSubmitted] = useState<any>(null); const [analytics,setAnalytics] = useState<Analytics | null>(null);
 const loadAnalytics = () => fetch(`${API}/analytics`).then(r=>r.json()).then(setAnalytics);
 useEffect(() => { loadAnalytics(); }, []);
 useEffect(() => { if (page !== 'quiz' || submitted || !started) return; const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000); return ()=>clearInterval(t); },[page,submitted,started]);
 useEffect(() => { if(seconds===0 && page==='quiz' && !submitted && questions.length) submit(); },[seconds]);
 async function begin(targetCategory = category) { setCategory(targetCategory); const q=await fetch(`${API}/questions?category=${encodeURIComponent(targetCategory)}&limit=10`).then(r=>r.json()); setQuestions(q); setAnswers({}); setCurrent(0); setSubmitted(null); setSeconds(600); setStarted(new Date().toISOString()); setPage('quiz'); }
 async function submit() { if (!questions.length || submitted) return; const payload={startedAt:started,durationSeconds:600-seconds,answers:questions.map(q=>({questionId:q.id,selectedOption:answers[q.id] ?? -1}))}; const result=await fetch(`${API}/attempts`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()); setSubmitted(result); loadAnalytics(); }
 const q=questions[current]; const scorePct=submitted ? Math.round(100*submitted.score/submitted.total) : 0;
 return <div className="app"><header><div className="brand"><span>✦</span> AptiPrep</div><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}>Home</button><button className={page==='learn'?'active':''} onClick={()=>setPage('learn')}>Learn</button><button className={page==='analytics'?'active':''} onClick={()=>{setPage('analytics');loadAnalytics()}}>Insights</button></nav><div className="free">Free aptitude prep</div></header>
 {page==='home' && <main className="academy"><section className="academy-hero"><p className="eyebrow">YOUR APTITUDE PREP SPACE</p><h1>Learn the logic.<br/><em>Build the speed.</em></h1><p>Start from the basics, practise one skill at a time, and take a timed test only when you feel ready.</p><div className="hero-actions"><button className="primary" onClick={()=>setPage('learn')}>Start learning →</button><button className="outline-light" onClick={()=>begin('All')}>Try a mixed test</button></div><div className="hero-metrics"><span><b>5</b> guided lessons</span><span><b>24+</b> solved questions</span><span><b>10 min</b> test mode</span></div></section><section className="loop"><p className="eyebrow">A SIMPLE WAY TO IMPROVE</p><h2>Learn. Practise. Test. Improve.</h2><div className="loop-grid"><button onClick={()=>setPage('learn')}><b>01</b><span>Learn</span><small>Formula, method, and worked examples.</small></button><button onClick={()=>begin('Quantitative')}><b>02</b><span>Practise</span><small>Build confidence with one topic at a time.</small></button><button onClick={()=>begin('All')}><b>03</b><span>Take a test</span><small>Try a timed mixed aptitude challenge.</small></button><button onClick={()=>{setPage('analytics');loadAnalytics()}}><b>04</b><span>Improve</span><small>See weak areas and choose your next lesson.</small></button></div></section><section className="daily"><div><p className="eyebrow">TODAY’S STUDY PLAN</p><h2>Start with one small win.</h2><p>Follow this simple sequence. It takes about 20 minutes.</p></div><div className="daily-list"><button onClick={()=>setPage('learn')}><span className="done">1</span><div><b>Learn Percentages</b><small>Formula + 3 worked examples · 12 min</small></div><i>Begin →</i></button><button onClick={()=>begin('Quantitative')}><span>2</span><div><b>Practise Quantitative</b><small>10 questions · untimed mindset</small></div><i>Start →</i></button><button onClick={()=>begin('All')}><span>3</span><div><b>Take your mixed test</b><small>10 questions · 10 minutes</small></div><i>Test →</i></button></div></section><section className="topic-path"><div><p className="eyebrow">CHOOSE A LEARNING PATH</p><h2>One skill at a time.</h2></div><div className="path-cards">{categories.slice(1).map((c,i)=><button key={c} onClick={()=>begin(c)}><span>0{i+1}</span><b>{c}</b><small>Learn the concept, then test yourself →</small></button>)}</div></section></main>}
 {page==='learn' && <main className="learn"><section className="learn-intro"><p className="eyebrow">LEARN THE METHOD</p><h1>Small steps.<br/><em>Clear solutions.</em></h1><p>Every lesson gives you the formula, a repeatable method, and three fully solved examples before you take a test.</p><button className="primary" onClick={()=>begin()}>I’m ready for a test →</button></section><section className="lesson-list">{lessons.map((lesson,i)=><article className="lesson" key={lesson.title}><div className="lesson-head"><span className="lesson-icon">{lesson.icon}</span><div><small>{lesson.area} · {lesson.time}</small><h2>{lesson.title}</h2></div><span className="lesson-no">0{i+1}</span></div><div className="formula"><b>Formula / rule</b><code>{lesson.formula}</code></div><h3>How to solve it</h3><ol>{lesson.steps.map(step=><li key={step}>{step}</li>)}</ol><h3>Worked examples</h3><div className="examples">{lesson.examples.map(([question,working,answer],index)=><div className="worked" key={question}><b>Example {index+1}: {question}</b><p><span>Working:</span> {working}</p><strong>{answer}</strong></div>)}</div><p className="lesson-tip"><b>Remember:</b> {lesson.tip}</p></article>)}</section></main>}
 {page==='quiz' && <main className="quiz">{!submitted && q && <><div className="quiz-top"><button className="back" onClick={()=>setPage('home')}>← Exit</button><div><b>Question {current+1}</b> of {questions.length}</div><div className="timer">◷ {String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</div></div><div className="progress"><i style={{width:`${((current+1)/questions.length)*100}%`}} /></div><article className="question"><span className="tag">{q.category} · {q.topic}</span><h2>{q.prompt}</h2><div className="options">{['option_a','option_b','option_c','option_d'].map((field,i)=><button key={field} onClick={()=>setAnswers({...answers,[q.id]:i})} className={answers[q.id]===i?'answer selected-answer':'answer'}><b>{letters[i]}</b>{q[field as keyof Question] as string}</button>)}</div><div className="quiz-actions"><button className="secondary" disabled={current===0} onClick={()=>setCurrent(current-1)}>Previous</button>{current===questions.length-1?<button className="primary" onClick={submit}>Finish quiz</button>:<button className="primary" onClick={()=>setCurrent(current+1)}>Next question →</button>}</div></article></>}
 {submitted && <section className="result"><div className="score-ring" style={{'--pct':scorePct} as CSSProperties}><b>{scorePct}%</b><span>score</span></div><p className="eyebrow">QUIZ COMPLETE</p><h1>{scorePct>=70?'Strong work!':'Keep building momentum.'}</h1><p>You got <b>{submitted.score} of {submitted.total}</b> questions correct.</p><div className="review">{questions.map((x,i)=>{const r=submitted.results[i]; return <div className={r.correct?'correct':'incorrect'} key={x.id}><b>{r.correct?'✓':'×'} {x.category}</b><span>{x.explanation}</span></div>})}</div><button className="primary" onClick={()=>{setPage('analytics');loadAnalytics()}}>See your insights →</button></section>}</main>}
 {page==='analytics' && <main className="insights"><section><p className="eyebrow">YOUR PERFORMANCE</p><h1>Progress that tells<br/>you what to do next.</h1>{analytics?.attempts.length ? <div className="chart"><Plot data={[{x:analytics.attempts.map((_,i)=>`Quiz ${i+1}`),y:analytics.attempts.map(a=>Math.round(a.score/a.total*100)),type:'scatter',mode:'lines+markers',line:{color:'#2f67f6',width:4},marker:{size:9}}]} layout={{autosize:true,height:280,margin:{l:40,r:10,t:25,b:45},paper_bgcolor:'transparent',plot_bgcolor:'transparent',yaxis:{range:[0,100],ticksuffix:'%',gridcolor:'#e6e9f2'},xaxis:{fixedrange:true},showlegend:false}} config={{displayModeBar:false}} style={{width:'100%'}} /></div> : <div className="empty">Complete your first quiz to see a performance trend.</div>}</section><aside><h2>Skill breakdown</h2>{analytics?.byCategory.length ? analytics.byCategory.map(x=><div className="skill" key={x.category}><div><b>{x.category}</b><span>{x.accuracy}%</span></div><i><em style={{width:`${x.accuracy}%`}} /></i><small>{x.correct}/{x.total} correct</small></div>) : <p className="muted">No results yet.</p>}<h2 className="rec-title">Your next moves</h2>{analytics?.recommendations.map((x,i)=><div className="tip" key={x}><span>{i+1}</span>{x}</div>)}</aside></main>}
 </div>;
}
